"""initial for the teacher

Revision ID: 43a815259bd7
Revises: f635030d4e11
Create Date: 2026-09-28 23:59:21.583478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a815259bd7'
down_revision: Union[str, Sequence[str], None] = 'f635030d4e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='teacher_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teachers_email_lower', 'teachers', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('teacher_guidance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('guidance_text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_guidance_student_teacher_created', 'teacher_guidance', ['student_id', 'teacher_id', 'created_at'], unique=False)
    op.create_table('teacher_student_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='assignment_status'), server_default='ACTIVE', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_student_assignments_student_id', 'teacher_student_assignments', ['student_id'], unique=False)
    op.create_index('ix_teacher_student_assignments_teacher_id', 'teacher_student_assignments', ['teacher_id'], unique=False)
    op.create_index('uq_teacher_student_active_assignment', 'teacher_student_assignments', ['teacher_id', 'student_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_teacher_student_active_assignment', table_name='teacher_student_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_teacher_student_assignments_teacher_id', table_name='teacher_student_assignments')
    op.drop_index('ix_teacher_student_assignments_student_id', table_name='teacher_student_assignments')
    op.drop_table('teacher_student_assignments')
    op.drop_index('ix_teacher_guidance_student_teacher_created', table_name='teacher_guidance')
    op.drop_table('teacher_guidance')
    op.drop_index('ix_teachers_email_lower', table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
