"""align curriculum and learning schema

Revision ID: 69a4004373ab
Revises: db2e320aefe2
Create Date: 2026-10-04 18:13:04.592635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69a4004373ab'
down_revision: Union[str, Sequence[str], None] = 'db2e320aefe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The baseline declared this primary key as SERIAL, but the models and all
    # new dependent tables use UUID.  Drop the SERIAL default before changing
    # the type: PostgreSQL cannot cast the sequence expression to UUID.
    # This deployment has no learning-objective rows; a populated database
    # needs an explicit, business-approved old-id-to-UUID mapping first.
    op.execute("ALTER TABLE learning_objectives ALTER COLUMN id DROP DEFAULT")
    op.alter_column(
        "learning_objectives",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::text::uuid",
    )
    op.alter_column(
        "learning_objectives",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "learning_objectives",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_constraint("learning_objectives_lesson_id_fkey", "learning_objectives", type_="foreignkey")
    op.create_foreign_key(
        "fk_learning_objectives_lesson_id_lessons",
        "learning_objectives",
        "lessons",
        ["lesson_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table('teacher_guidance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('guidance_text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_guidance_student_teacher_created', 'teacher_guidance', ['student_id', 'teacher_id', 'created_at'], unique=False)
    op.create_table('teacher_student_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='assignment_status'), server_default='ACTIVE', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_student_assignments_student_id', 'teacher_student_assignments', ['student_id'], unique=False)
    op.create_index('ix_teacher_student_assignments_teacher_id', 'teacher_student_assignments', ['teacher_id'], unique=False)
    op.create_index('uq_teacher_student_active_assignment', 'teacher_student_assignments', ['teacher_id', 'student_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('adaptive_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.Enum('TEACH', 'REVISE', 'PRACTICE', 'ASSESS', 'PROGRESS', name='adaptive_action'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='adaptive_difficulty'), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('recent_performance', sa.Float(), nullable=False),
    sa.Column('attempts_at_decision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adaptive_decisions_student_topic', 'adaptive_decisions', ['student_id', 'topic_id', 'id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_started_at'), 'learning_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_learning_sessions_student_id'), 'learning_sessions', ['student_id'], unique=False)
    op.create_table('lesson_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_lesson_completions_student_lesson')
    )
    op.create_index(op.f('ix_lesson_completions_lesson_id'), 'lesson_completions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_completions_student_id'), 'lesson_completions', ['student_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('related_topic_id', sa.UUID(), nullable=True),
    sa.Column('adaptive_decision_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('REVIEW', 'PRACTICE', 'CONTINUE', 'REMEDIATE', 'ADVANCE', name='recommendation_type'), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='recommendation_priority'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='recommendation_difficulty'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'DISMISSED', 'SUPERSEDED', name='recommendation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adaptive_decision_id'], ['adaptive_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index('ix_recommendations_student_status', 'recommendations', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_recommendations_subject_id'), 'recommendations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_recommendations_topic_id'), 'recommendations', ['topic_id'], unique=False)
    op.create_index('uq_recommendations_open_student_topic_type', 'recommendations', ['student_id', 'topic_id', 'type'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'ACTIVE')"), sqlite_where=sa.text("status IN ('PENDING', 'ACTIVE')"))
    op.create_table('masteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('learning_objective_id', sa.UUID(), nullable=True),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('attempts_considered', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BEGINNING', 'DEVELOPING', 'PROFICIENT', 'MASTERED', name='mastery_status'), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts_considered >= 0', name='ck_masteries_attempts_nonneg'),
    sa.CheckConstraint('correct_attempts >= 0 AND correct_attempts <= attempts_considered', name='ck_masteries_correct_range'),
    sa.CheckConstraint('mastery_score >= 0 AND mastery_score <= 1', name='ck_masteries_score_range'),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['learning_objectives.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masteries_id'), 'masteries', ['id'], unique=False)
    op.create_index(op.f('ix_masteries_learning_objective_id'), 'masteries', ['learning_objective_id'], unique=False)
    op.create_index(op.f('ix_masteries_student_id'), 'masteries', ['student_id'], unique=False)
    op.create_index(op.f('ix_masteries_topic_id'), 'masteries', ['topic_id'], unique=False)
    op.create_index('uq_masteries_student_objective', 'masteries', ['student_id', 'learning_objective_id'], unique=True, postgresql_where=sa.text('learning_objective_id IS NOT NULL'), sqlite_where=sa.text('learning_objective_id IS NOT NULL'))
    op.create_index('uq_masteries_student_topic', 'masteries', ['student_id', 'topic_id'], unique=True, postgresql_where=sa.text('learning_objective_id IS NULL'), sqlite_where=sa.text('learning_objective_id IS NULL'))
    op.create_table('question_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('learning_objective_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_level'), nullable=False),
    sa.Column('template_text', sa.String(), nullable=False),
    sa.Column('parameter_definitions', sa.JSON(), nullable=False),
    sa.Column('answer_rule', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['learning_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_templates_difficulty'), 'question_templates', ['difficulty'], unique=False)
    op.create_index(op.f('ix_question_templates_learning_objective_id'), 'question_templates', ['learning_objective_id'], unique=False)
    op.create_index(op.f('ix_question_templates_lesson_id'), 'question_templates', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_question_templates_question_type'), 'question_templates', ['question_type'], unique=False)
    op.create_index(op.f('ix_question_templates_subject_id'), 'question_templates', ['subject_id'], unique=False)
    op.create_index(op.f('ix_question_templates_topic_id'), 'question_templates', ['topic_id'], unique=False)
    op.create_table('generated_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('learning_objective_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('generated_text', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['learning_objectives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['question_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_questions_learning_objective_id'), 'generated_questions', ['learning_objective_id'], unique=False)
    op.create_index(op.f('ix_generated_questions_lesson_id'), 'generated_questions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_generated_questions_session_id'), 'generated_questions', ['session_id'], unique=False)
    op.create_index(op.f('ix_generated_questions_subject_id'), 'generated_questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_generated_questions_template_id'), 'generated_questions', ['template_id'], unique=False)
    op.create_index(op.f('ix_generated_questions_topic_id'), 'generated_questions', ['topic_id'], unique=False)
    op.create_table('mastery_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mastery_id', sa.Integer(), nullable=False),
    sa.Column('attempt_ref', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=False),
    sa.Column('score_after', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mastery_id'], ['masteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mastery_id', 'attempt_ref', name='uq_mastery_history_mastery_attempt')
    )
    op.create_index('ix_mastery_history_mastery_id_id', 'mastery_history', ['mastery_id', 'id'], unique=False)
    op.add_column('subjects', sa.Column('academic_level_id', sa.UUID(), nullable=False))
    op.add_column('subjects', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_subjects_academic_level_id'), 'subjects', ['academic_level_id'], unique=False)
    op.create_foreign_key(
        'fk_subjects_academic_level_id_academic_levels',
        'subjects',
        'academic_levels',
        ['academic_level_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_subjects_academic_level_id_academic_levels', 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_academic_level_id'), table_name='subjects')
    op.drop_column('subjects', 'active')
    op.drop_column('subjects', 'academic_level_id')
    op.drop_constraint('fk_learning_objectives_lesson_id_lessons', 'learning_objectives', type_='foreignkey')
    op.create_foreign_key(op.f('learning_objectives_lesson_id_fkey'), 'learning_objectives', 'lessons', ['lesson_id'], ['id'])
    op.alter_column('learning_objectives', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('learning_objectives', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('learning_objectives', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index('ix_mastery_history_mastery_id_id', table_name='mastery_history')
    op.drop_table('mastery_history')
    op.drop_index(op.f('ix_generated_questions_topic_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_template_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_subject_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_session_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_lesson_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_learning_objective_id'), table_name='generated_questions')
    op.drop_table('generated_questions')
    op.drop_index(op.f('ix_question_templates_topic_id'), table_name='question_templates')
    op.drop_index(op.f('ix_question_templates_subject_id'), table_name='question_templates')
    op.drop_index(op.f('ix_question_templates_question_type'), table_name='question_templates')
    op.drop_index(op.f('ix_question_templates_lesson_id'), table_name='question_templates')
    op.drop_index(op.f('ix_question_templates_learning_objective_id'), table_name='question_templates')
    op.drop_index(op.f('ix_question_templates_difficulty'), table_name='question_templates')
    op.drop_table('question_templates')
    op.drop_index('uq_masteries_student_topic', table_name='masteries', postgresql_where=sa.text('learning_objective_id IS NULL'), sqlite_where=sa.text('learning_objective_id IS NULL'))
    op.drop_index('uq_masteries_student_objective', table_name='masteries', postgresql_where=sa.text('learning_objective_id IS NOT NULL'), sqlite_where=sa.text('learning_objective_id IS NOT NULL'))
    op.drop_index(op.f('ix_masteries_topic_id'), table_name='masteries')
    op.drop_index(op.f('ix_masteries_student_id'), table_name='masteries')
    op.drop_index(op.f('ix_masteries_learning_objective_id'), table_name='masteries')
    op.drop_index(op.f('ix_masteries_id'), table_name='masteries')
    op.drop_table('masteries')
    op.drop_index('uq_recommendations_open_student_topic_type', table_name='recommendations', postgresql_where=sa.text("status IN ('PENDING', 'ACTIVE')"), sqlite_where=sa.text("status IN ('PENDING', 'ACTIVE')"))
    op.drop_index(op.f('ix_recommendations_topic_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_subject_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_student_status', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_lesson_completions_student_id'), table_name='lesson_completions')
    op.drop_index(op.f('ix_lesson_completions_lesson_id'), table_name='lesson_completions')
    op.drop_table('lesson_completions')
    op.drop_index(op.f('ix_learning_sessions_student_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_started_at'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index('ix_adaptive_decisions_student_topic', table_name='adaptive_decisions')
    op.drop_table('adaptive_decisions')
    op.drop_index('uq_teacher_student_active_assignment', table_name='teacher_student_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_teacher_student_assignments_teacher_id', table_name='teacher_student_assignments')
    op.drop_index('ix_teacher_student_assignments_student_id', table_name='teacher_student_assignments')
    op.drop_table('teacher_student_assignments')
    op.drop_index('ix_teacher_guidance_student_teacher_created', table_name='teacher_guidance')
    op.drop_table('teacher_guidance')
    # ### end Alembic commands ###
